title: Alison Peard
url: "https://alisonpeard.github.io"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://alisonpeard.github.io"
footer_text: "Page design by Ankit Sultana"

ins_logo: opsis+eci+Oxford-rgb.png

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Home"
   link: "https://alisonpeard.github.io"
 - name: "Resume"
   link: "cv.pdf"
 - name: "Contact"
   link: "contact"
